services:
    hacfi_aws.event_listener.resolve_parameters_listener:
        class: "hacfi\AwsBundle\EventListener\ResolveParametersListener"
        calls:
            - [setContainer, ["@service_container"]]
